#!/usr/bin/env python3

import os, glob, sys, subprocess


# ---------------------------------------------------------------------- #
# This function gets the name of the latest folder generated by the      #
# efabless flow                                                          #
# ---------------------------------------------------------------------- #
def get_latest ():
    list_of_folders = glob.glob("runs/*") 
    latest_folder = max(list_of_folders, key=os.path.getctime)
    return latest_folder



# ----------------------------- Main Function -------------------------- #
def main ():


    # Module name and the location of latest run
    # module_name = sys.argv[1]
    module_name = sys.argv[1]
    latest_folder = get_latest()
    
    # move the gds file to design directory
    subprocess.call("cp " + latest_folder + "/results/signoff/" + module_name + ".klayout.gds" + " " + module_name + ".gds", shell=True) 


if __name__ == "__main__":
    main ()

